export const REQUEST_DETAIL_INFO = 'REQUEST_DETAIL_INFO';
export const FETCH_DETAIL_INFO = 'FETCH_DETAIL_INFO';
export const RECEIVE_DETAIL_INFO = 'RECEIVE_DETAIL_INFO';

//recommend
export const RECEIVE_RECOMMEND_INFO = 'RECEIVE_RECOMMEND_INFO';
//banner
export const RECEIVE_BANNERS_INFO = 'RECEIVE_BANNERS_INFO';
//
export const RECEIVE_RESTAURANTS_INFO = "RECEIVE_RESTAURANTS_INFO"